server:        #端口号
  port: 8081
spring:
  application:
    name: drug
eureka:      #eureka地址
  client:
    service-url:
      default-zone: http://127.0.0.1:8761/eureka
feign:        #启动feign的熔断器功能
  hystrix:
    enabled: true